UPDATE subjects SET name = "Project 2.1 Embedded Systems" WHERE id = 1;
UPDATE subjects SET name = "Python" WHERE id = 2;
UPDATE subjects SET name = "Computer Architecture & Design" WHERE id = 3;
UPDATE subjects SET name = "Embedded Systems Lab" WHERE id = 4;
UPDATE subjects SET name = "Communication I" WHERE id = 5;
UPDATE subjects SET name = "Project 2.2 IT Infrastructures" WHERE id = 6;
UPDATE subjects SET name = "Operating Systems" WHERE id = 7;
UPDATE subjects SET name = "Computer Networking" WHERE id = 8;
UPDATE subjects SET name = "Research I: Strategies and Methods" WHERE id = 9;
UPDATE subjects SET name = "Intercultural Communication" WHERE id = 10;
UPDATE subjects SET name = "Project 2.3 Software Engineering" WHERE id = 11;
UPDATE subjects SET name = "OOP3 and Design Patterns" WHERE id = 12;
UPDATE subjects SET name = "Algorithms and Data Structures" WHERE id = 13;
UPDATE subjects SET name = "Academic Writing" WHERE id = 14;
UPDATE subjects SET name = "Discrete Mathematics" WHERE id = 15;
UPDATE subjects SET name = "Project 2.4 Web & Mobile" WHERE id = 16;
UPDATE subjects SET name = "Web & Mobile Services" WHERE id = 17;
UPDATE subjects SET name = "Research II" WHERE id = 18;
UPDATE subjects SET name = "Linear Algebra" WHERE id = 19;
UPDATE subjects SET name = "Communication II" WHERE id = 20;

UPDATE assignments SET name = "Project - Project 2.1 Embedded Systems", credits = 3 WHERE id = 1;
UPDATE assignments SET name = "Exam - Python", credits = 3 WHERE id = 2;
UPDATE assignments SET name = "Exam - Computer Architecture & Design", credits = 4 WHERE id = 3;
UPDATE assignments SET name = "Lab - Embedded Systems Lab", credits = 3 WHERE id = 4;
UPDATE assignments SET name = "Report - Communication I", credits = 2 WHERE id = 5;
UPDATE assignments SET name = "Project - Project 2.2 IT Infrastructures", credits = 2 WHERE id = 6;
UPDATE assignments SET name = "Exam - Operating Systems", credits = 4 WHERE id = 7;
UPDATE assignments SET name = "Exam - Computer Networking", credits = 4 WHERE id = 8;
UPDATE assignments SET name = "Exam - Research I: Strategies and Methods", credits = 3 WHERE id = 9;
UPDATE assignments SET name = "Report - Intercultural Communication", credits = 2 WHERE id = 10;
UPDATE assignments SET name = "Project - Project 2.3 Software Engineering", credits = 4 WHERE id = 11;
UPDATE assignments SET name = "Exam - OOP3 and Design Patterns", credits = 3 WHERE id = 12;
UPDATE assignments SET name = "Exam - Algorithms and Data Structures", credits = 3 WHERE id = 13;
UPDATE assignments SET name = "Report - Academic Writing", credits = 2 WHERE id = 14;
UPDATE assignments SET name = "Exam - Discrete Mathematics", credits = 3 WHERE id = 15;
UPDATE assignments SET name = "Project - Project 2.4 Web & Mobile", credits = 3 WHERE id = 16;
UPDATE assignments SET name = "Exam - Web & Mobile Services", credits = 3 WHERE id = 17;
UPDATE assignments SET name = "Report - Research II", credits = 4 WHERE id = 18;
UPDATE assignments SET name = "Exam - Linear Algebra", credits = 3 WHERE id = 19;
UPDATE assignments SET name = "Report - Communication II", credits = 2 WHERE id = 20;

truncate grades;

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 1, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 1, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 1, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 1, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 1, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 1, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 1, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 1, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 1, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 1, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 1, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 1, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 1, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 1, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 1, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 1, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 1, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 1, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 1, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 1, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 2, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 2, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 2, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 2, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 2, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 2, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 2, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 2, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 2, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 2, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 2, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 2, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 2, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 2, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 2, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 2, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 2, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 2, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 2, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 2, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 3, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 3, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 3, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 3, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 3, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 3, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 3, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 3, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 3, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 3, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 3, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 3, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 3, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 3, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 3, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 3, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 3, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 3, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 3, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 4, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 4, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 4, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 4, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 4, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 4, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 4, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 4, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 4, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 4, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 4, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 4, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 4, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 4, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 4, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 4, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 4, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 4, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 4, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 4, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 5, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 5, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 5, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 5, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 5, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 5, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 5, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 5, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 5, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 5, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 5, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 5, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 5, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 5, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 5, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 5, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 5, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 5, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 5, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 5, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 6, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 6, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 6, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 6, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 6, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 6, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 6, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 6, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 6, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 6, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 6, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 6, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 6, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 6, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 6, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 6, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 6, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 6, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 6, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 6, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 7, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 7, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 7, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 7, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 7, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 7, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 7, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 7, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 7, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 7, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 7, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 7, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 7, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 7, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 7, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 7, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 7, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 7, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 7, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 7, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 8, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 8, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 8, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 8, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 8, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 8, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 8, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 8, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 8, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 8, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 8, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 8, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 8, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 8, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 8, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 8, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 8, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 8, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 8, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 8, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 9, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 9, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 9, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 9, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 9, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 9, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 9, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 9, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 9, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 9, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 9, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 9, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 9, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 9, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 9, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 9, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 9, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 9, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 9, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 9, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 10, 1, now(), now()); 
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 10, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 10, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 10, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 10, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 10, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 10, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 10, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 10, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 10, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 10, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 10, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 10, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 10, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 10, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 10, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 10, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 10, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 10, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 10, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 11, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 11, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 11, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 11, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 11, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 11, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 11, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 11, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 11, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 11, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 11, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 11, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 11, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 11, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 11, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 11, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 11, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 11, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 11, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 11, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),1, 12, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),2, 12, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),3, 12, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),4, 12, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),5, 12, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),6, 12, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),7, 12, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),8, 12, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),9, 12, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),10, 12, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),11, 12, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),12, 12, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),13, 12, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),14, 12, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),15, 12, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),16, 12, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),17, 12, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),18, 12, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),19, 12, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),20, 12, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 13, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 13, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 13, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 13, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 13, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 13, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 13, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 13, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 13, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 13, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 13, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 13, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 13, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 13, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 13, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 13, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 13, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 13, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 13, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 13, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),1, 14, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),2, 14, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),3, 14, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),4, 14, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),5, 14, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),6, 14, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),7, 14, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),8, 14, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),9, 14, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),10, 14, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),11, 14, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),12, 14, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),13, 14, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),14, 14, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),15, 14, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),16, 14, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),17, 14, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),18, 14, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),19, 14, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),20, 14, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 1, 15, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 2, 15, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 3, 15, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 4, 15, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 5, 15, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 6, 15, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 7, 15, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 8, 15, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 9, 15, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 10, 15, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 11, 15, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 12, 15, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 13, 15, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 14, 15, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 15, 15, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 16, 15, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 17, 15, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 18, 15, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 19, 15, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1), 20, 15, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),1, 16, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),2, 16, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),3, 16, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),4, 16, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),5, 16, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),6, 16, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),7, 16, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),8, 16, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),9, 16, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),10, 16, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),11, 16, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),12, 16, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),13, 16, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),14, 16, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),15, 16, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),16, 16, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),17, 16, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),18, 16, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),19, 16, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),20, 16, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),1, 17, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),2, 17, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),3, 17, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),4, 17, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),5, 17, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),6, 17, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),7, 17, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),8, 17, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),9, 17, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),10, 17, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),11, 17, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),12, 17, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),13, 17, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),14, 17, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),15, 17, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),16, 17, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),17, 17, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),18, 17, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),19, 17, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),20, 17, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),1, 18, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),2, 18, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),3, 18, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),4, 18, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),5, 18, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),6, 18, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),7, 18, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),8, 18, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),9, 18, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),10, 18, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),11, 18, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),12, 18, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),13, 18, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),14, 18, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),15, 18, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),16, 18, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),17, 18, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),18, 18, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),19, 18, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),20, 18, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),1, 19, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),2, 19, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),3, 19, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),4, 19, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),5, 19, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),6, 19, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),7, 19, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),8, 19, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),9, 19, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),10, 19, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),11, 19, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),12, 19, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),13, 19, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),14, 19, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),15, 19, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),16, 19, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),17, 19, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),18, 19, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),19, 19, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),20, 19, 20, now(), now());

INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),1, 20, 1, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),2, 20, 2, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),3, 20, 3, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),4, 20, 4, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),5, 20, 5, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),6, 20, 6, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),7, 20, 7, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),8, 20, 8, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),9, 20, 9, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),10, 20, 10, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),11, 20, 11, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),12, 20, 12, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),13, 20, 13, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),14, 20, 14, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),15, 20, 15, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),16, 20, 16, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),17, 20, 17, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),18, 20, 18, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),19, 20, 19, now(), now());
INSERT INTO `grades` (grade, assignment_id, student_id, recorded_by, created_at, updated_at) VALUES (ROUND(RAND()*(10-1)+1, 1),20, 20, 20, now(), now());

